on:
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodule Autosync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GLITONEA_CI_TOKEN }}
        submodules: true

    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'Submodule Autosync'
        git config --global user.email 'autosync@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GLITONEA_CI_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
